# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb",
         "Deck": "00_core.ipynb",
         "Hand": "00_core.ipynb",
         "find_defining_class": "00_core.ipynb"}

modules = ["card.py"]

doc_url = "https://saneshashank.github.io/deck_of_cards/"

git_url = "https://github.com/saneshashank/deck_of_cards/tree/master/"

def custom_doc_links(name): return None
